import{a as l,b as $,P as T}from"./assets/vendor-a6d4c47e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const p=Object.freeze({BASE_URL:"https://your-energy.b.goit.study/api",EXERCISES:"/exercises",RATING:"/rating",FILTERS:"/filters",QUOTE:"/quote",SUBSCRIPTION:"/subscription"}),w=document.querySelector(".daily-quote"),{BASE_URL:A,QUOTE:G}=p;l.defaults.baseURL=A;const O=async()=>{try{const t=await l.get(G);U(t.data)}catch(t){console.error(t)}},U=({author:t,quote:e})=>{w.innerHTML=`<p class="daily-quote-text">${e}</p>
    <h4 class="daily-quote-author">${t}</h4>`};O();const{BASE_URL:q,FILTERS:B}=p;l.defaults.baseURL=q;const x=async(t="Muscles",e=1,r=12)=>{const i=new URLSearchParams({filter:t,limit:r,page:e});return(await l.get(`${B}?${i}`)).data},a={body:document.querySelector("body"),groupListWrapper:document.querySelector(".group-list-wrapper"),groupList:document.getElementById("js-group-list"),groupListPagination:document.getElementById("js-group-list-pagination"),exercisesNavList:document.querySelectorAll(".exercises__nav-item"),exercisesWrapper:document.querySelector(".exercises-list-wrapper")},L="selected-category",f="selected-group",d="is-exercises-list-visible",y="group-page",E="exercises-page",S="exercises-keyword",M="Muscles";class F{setExercisesListVisible(){sessionStorage.setItem(d,"true")}setExercisesListHidden(){sessionStorage.setItem(d,"false")}isExercisesListVisible(){return sessionStorage.getItem(d)==="true"}setFilterCategory(e){sessionStorage.setItem(L,e)}getFilterCategory(){return sessionStorage.getItem(L)??M}setGroup(e){sessionStorage.setItem(f,e)}getGroup(){return sessionStorage.getItem(f)??""}setGroupPage(e){sessionStorage.setItem(y,e.toString())}getGroupPage(){const e=sessionStorage.getItem(y);return e?Number(e):1}getExercisesPage(){const e=sessionStorage.getItem(E);return e?Number(e):1}setExercisesPage(e){sessionStorage.setItem(E,e.toString())}setExercisesKeyword(e){sessionStorage.setItem(S,e)}getExercisesKeyword(){return sessionStorage.getItem(S)??""}}const n=new F;function N(t){return t.map(({filter:e,name:r,imgURL:i})=>{const s=`data-filter="${e}"`,o=`data-group="${r}"`;return`
        <li class="group-list-card" ${s} ${o}>
          <img class="group-list-card-img" src="${i}" alt="${e} - ${r}" ${s} ${o}></img>
          <div class="group-list-card-info" ${s} ${o}>
          <h2 class="group-list-card-title" ${s} ${o}>${r}</h2>
          <p class="group-list-card-text" ${s} ${o}>${e}</p>
          </div>
        </li>
      `}).join("")}function j(){const t=a.groupList;t.style.opacity="0",$({targets:t,opacity:[0,1],duration:300,easing:"easeOutQuad",complete:()=>{a.groupListPagination.style.display="flex"}})}function P(t,e){t.innerHTML="",j(),t.insertAdjacentHTML("beforeend",N(e))}function H({currentPage:t,perPage:e,totalItems:r,totalPages:i,onChange:s}){const o="js-group-list-pagination",c=a.groupListPagination;i>1&&!n.isExercisesListVisible()?c.classList.remove("is-hidden"):c.classList.add("is-hidden");const g={page:Number(t),itemsPerPage:e,totalItems:r,centerAlign:!0,template:{page:'<button href="#">{{page}}</button>',currentPage:'<button href="#" class="is-active">{{page}}</button>',moveButton:'<button href="#" class="is-hidden"></button>',disabledMoveButton:'<button href="#" class="is-hidden"></button>',moreButton:'<button href="#" class="is-hidden"></button>'}};new T(o,g).on("beforeMove",u=>{const R=u.page;s(R)})}async function D(t){const e=n.getFilterCategory(),r=await x(e,t),{results:i}=r,s=a.groupList;P(s,i)}async function h({page:t,filter:e}){const r=await x(e,t),{results:i,page:s,perPage:o,totalPages:c}=r,g=c*o;H({currentPage:s,perPage:o,totalItems:g,totalPages:c,onChange:u=>{n.setGroupPage(u),D(u)}});const m=a.groupList;P(m,i)}function b(){n.setExercisesListVisible(),a.groupListWrapper.classList.add("is-hidden"),a.exercisesWrapper.classList.remove("is-hidden")}function C(){n.setExercisesListHidden(),a.groupListWrapper.classList.remove("is-hidden"),a.exercisesWrapper.classList.add("is-hidden")}const W=document.querySelector(".exercises_nav"),V=async t=>{try{let e=t.target,r=document.querySelector(".exercises__nav-item-current");((o,c)=>{o.classList.remove("exercises__nav-item-current"),c.classList.add("exercises__nav-item-current")})(r,e);const s=t.target.textContent.trim();a.groupList.innerHTML="",C(),n.setFilterCategory(s),n.setGroupPage(1),n.setExercisesPage(1),n.setExercisesKeyword(""),a.groupListPagination.style.display="none",h({page:1,filter:s})}catch(e){console.error(e)}};W.addEventListener("click",V);const{BASE_URL:Q,EXERCISES:K}=p;l.defaults.baseURL=Q;const I=async(t,e,r=1,i=10)=>{const s=new URLSearchParams({[t]:e,limit:i,page:r});return(await l.get(`${K}?${s}`)).data},X=document.querySelector(".exercises_search-img"),k=async()=>{const t=await I("abs","heel");console.log(t.data)};X.addEventListener("click",k);function Y(t){return t.map(({name:e})=>`<li class="exercise-card">
          <div>
            <div>Name - ${e}</div>
          </div>
        </li>`).join("")}function z(t,e){if(t.innerHTML="",!e||e.length===0){t.insertAdjacentHTML("beforeend",`<li class="error-card">
        There are no exercises matching your search. Please try another term.
      </li>`);return}t.insertAdjacentHTML("beforeend",Y(e))}const J={MUSCLES:"muscles",BODY_PARTS:"bodyparts",EQUIPMENT:"equipment"};async function v(){let t=n.getFilterCategory(),e=n.getGroup();t=t.toLowerCase().split(" ").join(""),t===J.BODY_PARTS&&(t=t.slice(0,-1)),e=e==null?void 0:e.toLowerCase();const r=n.getExercisesPage(),i=await I(t,e,r);z(a.exercisesWrapper,i.results)}const Z=n.getGroupPage(),_=n.getFilterCategory();a.groupListPagination.style.display="none";h({page:Z,filter:_});n.isExercisesListVisible()?(v(),b()):C();a.exercisesNavList.forEach(t=>{t.textContent.trim()===_&&t.classList.add("exercises__nav-item-current")});a.groupList.addEventListener("click",t=>{let e=t.target.dataset.filter,r=t.target.dataset.group;r=r==null?void 0:r.toLowerCase(),e&&r&&(n.setGroup(r),n.setFilterCategory(e),v(),b())});
//# sourceMappingURL=commonHelpers2.js.map
